version: "3.3"
services:
  zookeeper:
    image: "docker.io/bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "docker.io/bitnami/kafka:2"
    ports:
      - "9092:9092"
      - "9093:9093"
      - "23456:23456"
    volumes:
      - kafka_data:/bitnami
    environment:
      - JMX_PORT=23456
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  # kafdrop:
  #   image: obsidiandynamics/kafdrop:3.27.0
  #   ports:
  #     - 9000:9000
  #   environment:
  #     - KAFKA_BROKERCONNECT=kafka:9092
  #     - JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
  #     - JMX_PORT=23456
  #   depends_on:
  #     - zookeeper
  #     - kafka
  kafkamanager:
    image: "kafkamanager/kafka-manager:latest"
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - 9001:9000
    depends_on:
      - zookeeper
      - kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local