// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Items struct {
	ID      int32         `json:"id"`
	Content sql.NullInt64 `json:"content"`
	UserID  sql.NullInt32 `json:"userID"`
}

type Users struct {
	ID        int32          `json:"id"`
	Username  string         `json:"username"`
	Email     sql.NullString `json:"email"`
	Pwd       string         `json:"pwd"`
	CreatedAt sql.NullTime   `json:"createdAt"`
	Staff     sql.NullBool   `json:"staff"`
}
